package sysConfig

// 配置key
const (
	AppPackShareUrl                    = "AppPackShareUrl"  //渠道推广下载地址
	AppDaownName                       = "AppDaownName"     //推广下载地址
	IpDaySendNum                       = "IpDaySendNum"     //0 不限制 大于0 每天同ip只能发短信这么多
	DeviceDaySendNum                   = "DeviceDaySendNum" //0 不限制 大于0 每天同设备只能发短信这么多
	AppUserShareUrl                    = "AppUserShareUrl"  //个人推广下载地址
	Currency                           = "Currency"         // app币种
	KeyAppLoginConfigV2                = "AppLoginConfigV2" // app login 配置信息
	KeyRestrictIPAndDeviceRewardConfig = "RestrictIPAndDeviceRewardConfig"
	AppOfficeRate                      = "AppOfficeRate"           // app 管理成本
	AppApiRate                         = "AppApiRate"              // app api 外接游戏成本
	AppApiAfunRate                     = "AppApiAfunRate"          // app api 内部游戏成本
	PayAgentNoticeUrl                  = "PayAgentNoticeUrl"       // payAgent 支付回调地址
	PayAgentPageUrl                    = "PayAgentPageUrl"         // payAgent H5支付页面地址
	PayAgentSuccessUrl                 = "PayAgentSuccessUrl"      // payAgent 支付成功跳转地址
	PayAgentFailedUrl                  = "PayAgentFailedUrl"       // payAgent 支付失败跳转地址
	KeyPayConfigKey                    = "PayConfig"               // 充值配置
	KeyPayLangConfig                   = "PayLangConfig"           // 充值相关多语言配置
	KeyWithdrawConfig                  = "WithdrawConfig"          // 提现配置
	PutGroupConfig                     = "PutGroupConfig"          // 提现类型分组配置
	VipPutConfig                       = "VipPutConfig"            // 提现限制配置
	MinPutServerCharge                 = "MinPutServerCharge"      // 最低提现手续费
	PutAutoAuditCfg                    = "PutAutoAduitCfg"         // 提现自动审批和代付打款配置
	PutOpenTimeCfg                     = "PutOpenTimeCfg"          // 提现时间限制配置
	KeyPayChannelClassCfg              = "PayChannelClassCfg"      // 充值通道分类配置
	KeyWithdrawChannelClassCfg         = "WithdrawChannelClassCfg" // 提现通道分类配置
	TelegramLoginConfig                = "TelegramLoginConfig"     // Telegram登录配置
	OneAllLoginConfig                  = "OneAllLoginConfig"       // OneAll登录配置
	AppPointRateKey                    = "AppPointRate"            // USDT兑换法币的汇率
	LoginSignKey                       = "LoginSignKey"            // 前端登录时签名密钥
	GameAgentUserPrefix                = "GameAgentUserPrefix"     // 外接游戏名字前缀
	KeyAccountVerifyKey                = "AccountVerifyKey"        // 账号验证配置
	KeyVipConfig                       = "VipConfig"               // vip配置
	KeyAgentBaseConfig                 = "AgentBaseConfig"         // 代理基础配置(有效用户相关)
	ClearCodeUserMaxPoint              = "ClearCodeUserMaxPoint"   //清空打码量的最大用户余额
	GameAgentExportGenerals            = "GameAgentExportGenerals" // 正式配置总代可以请求体验服外接游戏 格式 23,34
	KeyWinGameConfig                   = "WinGameConfig"           // 赢钱模块配置
	KeyUserCacheConfig                 = "UserCacheConfig"
	KeyTaskRuleConfig                  = "TaskRuleConfig"           // 任务规则配置,各类任务数量
	GchatDirtyWordsKey                 = "DirtyWords"               // gchat 脏词
	KeyExperiencePointConfig           = "KeyExperiencePointConfig" // 体验金配置
	KeyThirdReportConfig               = "ThirdReportConfig"        // 三方上报配置
	IsNewNoticePushAll                 = "IsNewNoticePushAll"       // 新公告是否全量通知用户
	KeyJobSchedConfig                  = "JobSchedConfig"           // 作业系统配置
	NewUserPeriodHour                  = "NewUserPeriodHour"        // 新用户期限（小时）
	KeyAutoLabelConfig                 = "AutoLabelConfig"          // 自动打标签配置
	IdentityRiskKey                    = "IdentityRisk"             // 用户身份风控配置
	ExtWhatsAuth                       = "ExtWhatsAuth"             // whatsapp登录配置
	CurrencyExchangeApi                = "CurrencyExchangeApi"      // 汇率Api配置
	OriginWatchGames                   = "OriginWatchGames"         // 自研游戏配置观战:[1011,1022]
	CpfUserBindLimitCount              = "CpfUserBindLimitCount"    // 同cpf 绑定用户数量
	KeyIdentifyTypeConfig              = "IdentifyTypeConfig"       // 证件类型配置
	KeyPutAccountTypeConfig            = "PutAccountTypeConfig"     // 提款账号类型配置
	KeyLotteryBattleConfig             = "LotteryBattle"            // 彩票大战
	KeyLotteryBattleIssueConfig        = "LotteryBattleIssue"       // 彩票大战奖期相关
	KeyLotteryIssueOpBotConfig         = "LotteryIssueOpBot"        // 彩票奖期机器人
	KeyBetPayConfig                    = "BetPayConfig"             // 新版betPay配置
	KeyPlatformCoinConfig              = "PlatformCoinConfig"       // 平台币配置
	KeyBonusCodeConfig                 = "BonusCodeConfig"          // 彩金打码配置（废弃）
	KeyNewBonusCodeConfig              = "NewBonusCodeConfig"       // 彩金打码配置
	KeyLaunchGameConfig                = "LaunchGameConfig"         // 拉起游戏统一配置
	ThirdGameMinPoint                  = "====="                    // 废弃
	WebPushPublicKey                   = "WebPushPublicKey"         // WebPush传给客户端的公钥
	WebPushPrivateKey                  = "WebPushPrivateKey"        // WebPush服务端私钥
	FirebaseCredentials                = "FirebaseCredentials"      // Firebase Admin SDK认证项目JSON数据
	KeyOpManagerAutoCleanConfig        = "OpManagerAutoCleanConfig" // 后台账号清理配置
	KeyAwsS3Config                     = "AwsS3Config"              // AWS S3接入相关配置
	KeyBetbyPromoFeed                  = "KeyBetbyPromoFeed"        // betby 同步数据配置
	KeyBetbyAppPromoFeed               = "KeyBetbyAppPromoFeed"     // betby APP拉取数据配置
	FilterWordConfig                   = "FilterWordConfig"         // 脏词过滤
	KeyKYCSerasaExperian               = "KeyKYCSerasaExperian"     // kyc SerasaExperian 配置信息
	KeyKYCBigDataCorp                  = "KeyKYCBigDataCorp"        // kyc bigDataCorp 配置信息
	KeyKYCAllowMe                      = "KeyKYCAllowMe"            // kyc allowme 配置信息
	KeyKYCSumSub                       = "KeyKYCSumSub"             // kyc sumsub 配置信息
	//KeyAppKycConfig                    = "AppKycConfig"                 // app的KYC配置KYC信息
	KeyKYCLegitimuz                 = "KeyKYCLegitimuz"              // kyc Legitimuz 配置信息
	KeySigapConfig                  = "SigapConfig"                  // 巴西sigap认证配置
	KeyOpsToolConfig                = "OpsToolConfig"                // 运维工具域名配置
	KeyAppTipsConfig                = "AppTipsConfig"                // app小费tips配置
	KeyUserShareConfig              = "UserShareUrlConfig"           // 分享链接配置
	KeyResponsibleConfig            = "ResponsibleConfig"            // 负责任的博彩开关配置
	KeyLocationTrustRadius          = "AppLocationTrustRadius"       // 地址位置 可信半径
	KeySportReportConfig            = "SportReportConfig"            // 牌照体育信息上报配置
	KeyAppFaceAuthConfig            = "AppFaceAuthConfig"            // 人脸识别开关
	KeyLongTimeNoLoginConfig        = "LongTimeNoLoginConfig"        // 用户长时间未登录通知
	KeyAppDefaultGeneralConfig      = "AppDefaultGeneralConfig"      // 盘口总代配置
	KeyDisableShareConfig           = "DisableShareConfig"           // 禁用分享配置
	KeyAwsS3ConfigV2                = "AwsS3ConfigV2"                // 存储桶上传配置
	KeyAppMergeConfig               = "AppMergeConfig"               // app和服配置
	KeyAppSafeBoxConfig             = "AppSafeBoxConfig"             // 保险箱配置
	KeyAndroidAppDownloadLinkConfig = "AndroidAppDownloadLinkConfig" // 安卓app下载连接配置
	KeyCheckUserOnlineConfig        = "CheckUserOnlineConf"          // 用户活跃认证检查配置
	KeyForceUserReLoginConfig       = "ForceUserReLoginConf"         // 强制用户重新登录验证配置
	KeyAppUserGoogleConfig          = "AppUserGoogleConfig"          // 平台谷歌认证码配置
	KeyAppUserAuthenticationConfig  = "AppUserAuthenticationConfig"  // 用户身份验证配置
	KeyHBCCoinConfig                = "HBCCoinConfig"                // 加密货币三方hbc币种配置
	KeyBRLISPBConfig                = "BRLISPBConfig"                // 巴西银行ISPB配置
	KeyOpenApiConfig                = "OpenApiConfig"                // 开放平台api
	KeyProviderGamePlatIdList       = "ProviderGamePlatIdList"       // 游戏库平台id
	KycCurrencyRecordConfig         = "CurrencyRecordConfig"         // 货币汇率打点

	// 后台用
	SmsproxyAlertConfigKey  = "SmsproxyAlertConfig"     // 短信告警配置
	DataCheckerTelegram     = "DataCheckTelegram"       // 数据核对小飞机
	HourReportTelegram      = "HourReportTelegram"      // 小时播报小飞机
	PutInfoType             = "PutInfoType"             // 开启的提现类型; 0.只开后台提现, 1.只开代付, 2.两种都开
	OfflineAgentGeneralCfg  = "OfflineAgentGeneralCfg"  // 代理总代配置
	UserLabelGroups         = "UserLabelGroups"         // 用户标签组
	PayRepeatTime           = "PayRepeatTime"           // 后台手动充值，相应时间内，同一ID，同一金额的充值操作不能重复充值
	KeyDeleteUserInfoCfg    = "DeleteUserInfoCfg"       // 后台数据脚本，清理用户配置
	GoogleTranslateApiToken = "GoogleTranslateApiToken" // 谷歌翻译API密钥
	BackstageNoticeDomain   = "BackstageNoticeDomain"   // 后台回调域名

	KeyAutoPutConfigKey = "AutoPutConfigKey" // 自动提款配置
)
