// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"context"
	"github.com/aiden2048/pkg/public/httpHandle"
	"github.com/aiden2048/pkg/qgframe"
	"github.com/fasthttp/router"
	"github.com/valyala/fasthttp"
	{{.importPackages}}
)

func RegisterHttpHandlers()  fasthttp.RequestHandler{
	route := router.New()
	{{.routesAdditions}}
	return route.Handler
}
func RegisterPackHttpHandlers()  fasthttp.RequestHandler{
	route := router.New()
	{{.routesPackAdditions}}
	return route.Handler
}