// Code generated by goctl. DO NOT EDIT.
package handler

import (
	{{if .notOnlyEvents}}"context"
	"github.com/aiden2048/pkg/frame"
	"github.com/aiden2048/pkg/public/natsHandle"{{end}}
	{{if .hasEvent}}"github.com/aiden2048/common/public/events"
	"github.com/aiden2048/pkg/public/natsStream"{{end}}
	{{.importPackages}}
)

func RegisterHandlers()(err error) {
	{{.routesAdditions}}
	return
}